// <auto-generated />
using System;
using Finance.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Models.ContributionFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ContributionFrequencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Без повторения"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ежедневно"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Еженедельно"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ежемесячно"
                        });
                });

            modelBuilder.Entity("Finance.Models.FinancialGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_FinancialGoals_CategoryId");

                    b.HasIndex(new[] { "PriorityId" }, "IX_FinancialGoals_PriorityId");

                    b.HasIndex(new[] { "StatusId" }, "IX_FinancialGoals_StatusId");

                    b.HasIndex(new[] { "UserId" }, "IX_FinancialGoals_UserId");

                    b.ToTable("FinancialGoals");
                });

            modelBuilder.Entity("Finance.Models.GoalCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("GoalCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Покупки"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Сбережения"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Инвестиции"
                        });
                });

            modelBuilder.Entity("Finance.Models.GoalContribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FinancialGoalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FinancialGoalId" }, "IX_GoalGoalContributions_FinancialGoalId");

                    b.ToTable("GoalGoalContributions");
                });

            modelBuilder.Entity("Finance.Models.GoalPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinancialGoalId")
                        .HasColumnType("integer");

                    b.Property<int>("FrequencyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PlannedAmount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FinancialGoalId" }, "IX_GoalPlans_FinancialGoalId");

                    b.HasIndex(new[] { "FrequencyId" }, "IX_GoalPlans_FrequencyId");

                    b.ToTable("GoalPlans");
                });

            modelBuilder.Entity("Finance.Models.GoalStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("GoalStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Активна"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Достигнута"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Провалена"
                        });
                });

            modelBuilder.Entity("Finance.Models.Priority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Priorities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Низкий"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Средний"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Высокий"
                        });
                });

            modelBuilder.Entity("Finance.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Finance.Models.FinancialGoal", b =>
                {
                    b.HasOne("Finance.Models.GoalCategory", "Category")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Models.Priority", "Priority")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Models.GoalStatus", "Status")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Models.User", "User")
                        .WithMany("FinancialGoals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Priority");

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Finance.Models.GoalContribution", b =>
                {
                    b.HasOne("Finance.Models.FinancialGoal", "FinancialGoal")
                        .WithMany("GoalContributions")
                        .HasForeignKey("FinancialGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialGoal");
                });

            modelBuilder.Entity("Finance.Models.GoalPlan", b =>
                {
                    b.HasOne("Finance.Models.FinancialGoal", "FinancialGoal")
                        .WithMany("GoalPlans")
                        .HasForeignKey("FinancialGoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Finance.Models.ContributionFrequency", "Frequency")
                        .WithMany("GoalPlans")
                        .HasForeignKey("FrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialGoal");

                    b.Navigation("Frequency");
                });

            modelBuilder.Entity("Finance.Models.ContributionFrequency", b =>
                {
                    b.Navigation("GoalPlans");
                });

            modelBuilder.Entity("Finance.Models.FinancialGoal", b =>
                {
                    b.Navigation("GoalContributions");

                    b.Navigation("GoalPlans");
                });

            modelBuilder.Entity("Finance.Models.GoalCategory", b =>
                {
                    b.Navigation("FinancialGoals");
                });

            modelBuilder.Entity("Finance.Models.GoalStatus", b =>
                {
                    b.Navigation("FinancialGoals");
                });

            modelBuilder.Entity("Finance.Models.Priority", b =>
                {
                    b.Navigation("FinancialGoals");
                });

            modelBuilder.Entity("Finance.Models.User", b =>
                {
                    b.Navigation("FinancialGoals");
                });
#pragma warning restore 612, 618
        }
    }
}
